deployments:
- name: null
  version: null
  tags: []
  description: null
  schedule:
    cron: 0 9 3 * *
    timezone: UTC
  flow_name: null
  entrypoint: null
  parameters: {}
  work_pool:
    name: null
    work_queue_name: null
    job_variables: {}
